<<<<<<< HEAD
version: '2'

volumes:
  nextcloud:
  db:
  swift:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=111
      - MYSQL_PASSWORD=111
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always

  swift:
    image: swift
    ports:
      - 8081:80
    links:
      - app
    volumes:
      - swift:/srv
    restart: always
=======
version: '2.1'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local
  swift_data:
    driver: local
  keystone_db:
    driver: local

services:
  owncloud:
    image: owncloud/server:latest
    restart: always
    hostname: owncloud
    dns:
      - 8.8.8.8
    ports:
      - ${HTTPS_PORT}:443
      - ${HTTP_PORT}:80
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_UTF8MB4_ENABLED=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - files:/mnt/data


  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=owncloud
      - MARIADB_USERNAME= 
      - MARIADB_PASSWORD=owncloud
      - MARIADB_DATABASE=owncloud
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
      - MARIADB_INNODB_LARGE_PREFIX=ON
      - MARIADB_INNODB_FILE_FORMAT=Barracuda
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

  redis:
    image: webhippie/redis:latest
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis

  mysql_db:
    image: mariadb
    volumes:
      - keystone_db:/var/lib/mysql
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_ROOT_PASSWORD=Class123456

  kstone:
    depends_on:
      - mysql_db
    image: krystism/openstack-keystone
    hostname: kstone
    dns:
      - 8.8.8.8
    links:
      - mysql_db
    ports:
      - "35357:35357"
      - "5000:5000"
    restart: always
    environment:
      - OS_TENANT_NAME:admin
      - OS_USERNAME:admin
      - OS_PASSWORD:Class123456

  swift:
    image: serverascode/swift-onlyone
    hostname: swift
    dns:
      - 8.8.8.8
    ports:
      - 8080:8080
    links:
      - owncloud
      - kstone
    volumes:
      - swift_data:/srv
      - ./conf.d/proxy-server.conf:/etc/swift/proxy-server.conf
    depends_on: 
      - kstone
    
>>>>>>> 9bacea0c0cada48ab6eb9218fad5013367aaf803
