- name: install_epel_repo
  yum:
    name: epel-release
    state: present
    update_cache: yes

- name: check registered the repository of nginx-release
  shell: rpm -qa | grep nginx-release
  register: result
  ignore_errors: True
  always_run: yes
  changed_when: no

- name: add repository nginx-release (CentOS6/CentOS7)
  yum: 
    name: http://nginx.org/packages/centos/{{ansible_distribution_major_version}}/noarch/RPMS/nginx-release-centos-{{ansible_distribution_major_version}}-0.el{{ansible_distribution_major_version}}.ngx.noarch.rpm
    state: present
  when: result|failed
  register: nginx_repo_installed

- name: disable_the_repository
  replace: 
    dest: /etc/yum.repos.d/nginx.repo 
    regexp: "enabled *= *1" 
    replace: "enabled=0"
  ignore_errors: True

- name: install_nginx
  yum:
    name: nginx
    enablerepo: nginx
    state: present
  when: nginx_repo_installed
  register: nginx_installed
  notify:
    - start_nginx

- name: copy_src_config
  when: nginx_installed|success
  copy:
    src: h5bp
    dest: /etc/nginx
    owner: root
    group: root

- name: disable_defaulte_site
  when: nginx_installed|success
  file: 
    dest: /etc/nginx/sites-enabled/default
    state: absent


- name: create_site_config_directory
  when: nginx_installed|success
  file: 
    path: "{{item}}"
    recurse: yes
    state: directory
  with_items: [ "/etc/nginx/sites-available/" ,"/etc/nginx/sites-enabled/"]
  register: site_dirctory

- name: add_site_config
  when: site_dirctory|success
  register: copy_site_config
  template: 
    src: sysnet.local.conf 
    dest: /etc/nginx/sites-available/{{ domain }}.conf
    owner: root
    group: root

- name: enable_site_config
  when: site_dirctory|success
  file: 
    src: /etc/nginx/sites-available/{{ domain }}.conf 
    dest: /etc/nginx/sites-enabled/{{ domain }}.conf 
    state: link

- name: create_web_root
  when: nginx_installed|success
  file: 
    dest: /var/www/{{ domain }}/public 
    mode: 0775 
    state: directory 
    owner: nginx 
    group: nginx
  notify:
    - reload_nginx

- name: fix_permissions
  when: nginx_installed|success
  file: 
    dest: /var/www/{{ domain }} 
    mode: 0775 
    state: directory 
    owner: nginx 
    group: nginx 
    recurse: yes
  notify:
    - reload_nginx